### ISSUE TITLE
Check if provided route config is correct

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#116]
Currently docs directs to use: 

```yml
ongr_api_routing:
    resource: @ONGRApiBundle/Resources/config/routing.yml
    prefix: /api
```

I think we should consider to propose use:

```yml
ongr_api_main_route:
    resource: .
    type: ongr_api
    prefix: api/
```
