### ISSUE TITLE
Add ?pretty

### ISSUE THREAD

**Issue by jkrug** [ongr-io/ApiBundle#81]
Could we add the pretty parameter to format the output. That would be very helpful for debugging.

**Comment by saimaz** [comment]
+1 good idea, lets do this.

**Comment by murnieza** [comment]
It will not be the "small" task to add `?pretty`, because currently we use several serializers and they are configured not in request handling phase. It is possible to write some event listeners and reconfigure settings depending on request, but I am not sure if we really need it.

So question is do we want to have additional logic layer for feature like this.

It is possible to get "pretty" `json` response though. Disadvantage is that you can not control it with request parameters anymore. Following configuration has to be added:

```yml
jms_serializer:
    visitors:
        json:
            options: JSON_PRETTY_PRINT
```
