### ISSUE TITLE
Make sure correct routes are generated from the config in DI Extension

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#94]
Look at the configuration docs: https://github.com/ongr-io/ApiBundle/blob/9610b53ea5bc7dd3390b4be27e7a94452a3e4cb8/Resources/doc/configuration.md

Say we have: 
```yml
ongr_api:
   output_format: json
   version_in_url: true
   versions:
       v3:
           endpoints:
               person:
                   repository: es.manager.default.person
                   allow_extra_fields: false
                   allow_get_all: true
```

Routes we expect to have generated dynamicaly:
/api/v1/person POST 
/api/v1/person/{id} PUT 
/api/v1/person/{id} GET
/api/v1/person/_all GET
/api/v1/person/{id} DELETE
/api/v1/person/_batch POST 

Routes must be pointed to specific `RestController` action.
